# Generated by Django 6.0.4 on 2026-04-22 05:52

import datetime
import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], max_length=4)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be in format XXXXXX/XX/X (digits only)', regex='^\\d{6}/\\d{2}/\\d{1}$')])),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeathCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('date_of_death', models.DateField()),
                ('other_findings', models.TextField(blank=True, null=True)),
                ('place_of_death', models.CharField(max_length=200)),
                ('cause_of_death', models.CharField(max_length=500)),
                ('date_issued', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('certifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('deceased', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death_certificate', to='records.deceased')),
            ],
        ),
        migrations.CreateModel(
            name='Certifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry_date', models.DateField()),
                ('date_certified', models.DateField(default=datetime.date.today)),
                ('certifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deceased', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certifiers', to='records.deceased')),
            ],
        ),
    ]
