# Generated by Django 6.0.4 on 2026-04-22 10:32

import datetime
import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], max_length=4)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be in format XXXXXX/XX/X (digits only)', regex='^\\d{6}/\\d{2}/\\d{1}$')])),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuneralHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Other', 'Other')], max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeathRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_of_death', models.DateField()),
                ('other_findings', models.TextField(blank=True, null=True)),
                ('place_of_death', models.CharField(max_length=200)),
                ('cause_of_death', models.CharField(max_length=500)),
                ('date_issued', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('certifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('deceased', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death_records', to='records.deceased')),
            ],
        ),
        migrations.CreateModel(
            name='DeathCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('death_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='records.deathrecords')),
            ],
        ),
        migrations.CreateModel(
            name='BurialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burial_date', models.DateField()),
                ('burial_location', models.CharField(max_length=300)),
                ('burial_plot_number', models.CharField(blank=True, max_length=50, null=True)),
                ('death_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='burial', to='records.deathrecords')),
            ],
        ),
        migrations.CreateModel(
            name='Certifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry_date', models.DateField()),
                ('date_certified', models.DateField(default=datetime.date.today)),
                ('certifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deceased', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certifiers', to='records.deceased')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Private Practice', 'Private Practice'), ('Pharmacy', 'Pharmacy'), ('Other', 'Other')], max_length=20)),
                ('other_institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_of_institution', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('postal_box', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('certifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='records.certifiers')),
            ],
        ),
        migrations.CreateModel(
            name='DeceasedFuneralHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.deceased')),
                ('funeral_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.funeralhome')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('deceased',), name='unique_current_funeral_home_per_deceased')],
            },
        ),
        migrations.CreateModel(
            name='DeceasedNextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.deceased')),
                ('next_of_kin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.nextofkin')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('deceased',), name='unique_primary_nok_per_deceased')],
            },
        ),
    ]
