# Generated by Django 6.0.5 on 2026-05-18 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deathrecords',
            options={'permissions': [('can_approve_deathrecord', 'Can approve death record')]},
        ),
        migrations.AlterField(
            model_name='deathrecords',
            name='deceased',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death_record', to='records.deceased'),
        ),
    ]
