# Generated by Django 6.0.4 on 2026-04-22 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_nextofkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Private Practice', 'Private Practice'), ('Pharmacy', 'Pharmacy'), ('Other', 'Other')], max_length=20)),
                ('other_institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_of_institution', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('postal_box', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('certifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='records.certifiers')),
            ],
        ),
    ]
