# Generated by Django 6.0.4 on 2026-04-22 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_medicalinstitution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeceasedFuneralHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.deceased')),
                ('funeral_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.funeralhome')),
            ],
        ),
        migrations.CreateModel(
            name='DeathRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('certifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('death_certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.deathcertificate')),
                ('deceased', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death_record', to='records.deceased')),
                ('next_of_kin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.nextofkin')),
                ('deceased_funeral_home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.deceasedfuneralhome')),
            ],
        ),
        migrations.CreateModel(
            name='DeceasedNextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.deceased')),
                ('next_of_kin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.nextofkin')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('deceased',), name='unique_primary_nok_per_deceased')],
            },
        ),
        migrations.AddConstraint(
            model_name='deceasedfuneralhome',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('deceased',), name='unique_current_funeral_home_per_deceased'),
        ),
    ]
