# Generated by Django 6.0.4 on 2026-04-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_funeralhome_deceasedfuneralhome_deathrecords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextofkin',
            name='deceased',
        ),
    ]
